### PR TITLE
update README, add examples

### PR DESCRIPTION
**Pull request by jgpawletko**
* Clean up `README.md`
* Add `Rsbe::Client::SearchResults` examples.

### CODE REVIEW

**Comment by jgpawletko** [comment]
Hi @eshadatta , @rrasch ,

Please take a look at this PR when you get a chance and let me know if you have questions or would like clarifications on using the `Rsbe::Client::SearchResults` class.   
Please feel free to merge the PR if everything looks OK. 

The examples file is [here](https://github.com/NYULibraries/rsbe-client/blob/chore/update-doc/examples.md) in this repo.
Another example is [here](https://v3.es.its.nyu.edu/jgp222/rsbe-se-updater/blob/master/lib/rsbe/se/updater/runner.rb#L64-66).

Thanks for your time!

Cc: @ericsted

**Comment by eshadatta** [comment]
@jgpawletko ,

This is super clear to me. Thanks for the very detailed documentation. I also looked at the other [example](https://v3.es.its.nyu.edu/jgp222/rsbe-se-updater/blob/master/lib/rsbe/se/updater/runner.rb#L64-66) and had a question about the [use case](https://v3.es.its.nyu.edu/jgp222/rsbe-se-updater/blob/master/lib/rsbe/se/updater/runner.rb#L74) where more than 1 se is returned for one digi id. You are returning an error right now, but what's the solution for it and how would it occur? Just curious. I'm happy to merge it but will wait till @rrasch has had a chance to take a look. Thanks!

**Comment by jgpawletko** [comment]
Hi @eshadatta ,
Thank you for reviewing the PR.  

Re: the [use case](https://v3.es.its.nyu.edu/jgp222/rsbe-se-updater/blob/master/lib/rsbe/se/updater/runner.rb#L74) where more than one `se` is returned for the same `digi_id`:
the `rsbe` database has a uniqueness constraint on the columns `coll_id` and `digi_id`.  Therefore, it is possible, but unlikely, that there could be two `se`s in different collections with the same `digi_id`.  If this occurs, we need to know about it, because we won't be able to tell which `se` to update.  The solution, for now, is to **fail noisily**.  Later, we will need to provide a means to disambiguate the `digi_id`.

**Comment by jgpawletko** [comment]
spoke with @rrasch during scrum and he said it is OK to merge.

**Pull request merged**
